# Generated by Django 4.2.4 on 2023-09-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0004_user_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_1',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_2',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_3',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
    ]
