# Generated by Django 4.2.4 on 2023-09-14 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0006_alter_cart_id_alter_cartitem_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variations',
            new_name='Variation',
        ),
    ]
