# Generated by Django 4.2.4 on 2023-09-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0009_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
