# Generated by Django 4.2.4 on 2023-09-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0011_tempuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='user_side.variation'),
        ),
    ]
