# Generated by Django 4.2.4 on 2023-09-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0012_cartitem_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
