# Generated by Django 4.2.4 on 2023-09-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0015_address_order_payment_orderproducts_order_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
    ]
