# Generated by Django 4.2.4 on 2023-10-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0022_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Accepted', max_length=10),
        ),
    ]
