# Generated by Django 4.2.4 on 2023-10-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0024_coupons_usercoupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Payment Failed', 'Payment Failed')], default='Accepted', max_length=20),
        ),
    ]
