# Generated by Django 4.2.4 on 2023-10-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0029_categoryoffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryOffer',
        ),
    ]
