# Generated by Django 4.2.4 on 2023-10-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0030_delete_categoryoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (e.g., 10.00 for 10% off)', max_digits=5, null=True),
        ),
    ]
