# Generated by Django 4.2.4 on 2023-10-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0031_product_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product price after discount (if applicable)', max_digits=10, null=True),
        ),
    ]
