# Generated by Django 4.2.4 on 2023-10-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0032_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
