# Generated by Django 4.2.4 on 2023-10-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0033_category_offer_alter_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='apply_category_offer',
            field=models.BooleanField(default=False),
        ),
    ]
