# Generated by Django 4.2.4 on 2023-10-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0034_product_apply_category_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='apply_category_offer',
            field=models.BooleanField(default=True),
        ),
    ]
