# Generated by Django 4.2.4 on 2023-10-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0035_alter_product_apply_category_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='apply_category_offer',
        ),
    ]
