# Generated by Django 4.2.4 on 2023-10-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0038_alter_reviewrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
