# Generated by Django 4.2.4 on 2023-10-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0040_reviewreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewreply',
            name='user',
        ),
    ]
