# Generated by Django 4.2.4 on 2023-10-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0041_remove_reviewreply_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewreply',
            name='status',
        ),
    ]
