# Generated by Django 4.2.4 on 2023-10-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0042_remove_reviewreply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreply',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
