# Generated by Django 4.2.4 on 2023-10-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0043_reviewreply_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewReply',
        ),
    ]
