# Generated by Django 4.2.4 on 2023-10-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0047_alter_order_order_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewReply',
        ),
    ]
