# Generated by Django 4.2.4 on 2023-10-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0048_delete_reviewreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='review_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
