# Generated by Django 4.2.4 on 2023-10-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0050_alter_product_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='offer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
