# Generated by Django 4.2.4 on 2023-10-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0052_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='return_reason',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
