# Generated by Django 4.2.4 on 2023-10-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0053_wallet_return_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
