# Generated by Django 4.2.4 on 2023-10-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0054_alter_wallet_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='return_reason',
        ),
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
