# Generated by Django 4.2.4 on 2023-10-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0055_remove_wallet_return_reason_order_return_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return Pending', 'Return Pending'), ('Returned', 'Returned'), ('Payment Failed', 'Payment Failed'), ('Order Failed', 'Order Failed')], default='Order Placed', max_length=20),
        ),
    ]
