# Generated by Django 4.2.4 on 2023-10-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0059_user_referral_code_referral'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
