# Generated by Django 4.2.4 on 2023-10-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0061_alter_contactus_content_alter_contactus_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='content',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='mobile',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
